//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace HP.ClearingCenter.Tests.HP.ClearingCenter.WebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MainInterfaceSoap", Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class MainInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ApiAuthenticationToken apiAuthenticationTokenValueField;
        
        private System.Threading.SendOrPostCallback AdviseClearingCenterProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClearedProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmReceivedProductsReceptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmClearedProductsReceptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback EchoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MainInterface() {
            this.Url = global::HP.ClearingCenter.Tests.Properties.Settings.Default.HP_ClearingCenter_Tests_HP_ClearingCenter_WebServices_MainInterface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ApiAuthenticationToken ApiAuthenticationTokenValue {
            get {
                return this.apiAuthenticationTokenValueField;
            }
            set {
                this.apiAuthenticationTokenValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AdviseClearingCenterProductCompletedEventHandler AdviseClearingCenterProductCompleted;
        
        /// <remarks/>
        public event GetReceivedProductsCompletedEventHandler GetReceivedProductsCompleted;
        
        /// <remarks/>
        public event GetClearedProductsCompletedEventHandler GetClearedProductsCompleted;
        
        /// <remarks/>
        public event ConfirmReceivedProductsReceptionCompletedEventHandler ConfirmReceivedProductsReceptionCompleted;
        
        /// <remarks/>
        public event ConfirmClearedProductsReceptionCompletedEventHandler ConfirmClearedProductsReceptionCompleted;
        
        /// <remarks/>
        public event EchoCompletedEventHandler EchoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiAuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://h41201.www4.hp.com/ClearingCenter.Web/WebServices/AdviseClearingCenterProd" +
            "uct", RequestNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", ResponseNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseResult AdviseClearingCenterProduct(AdviseClearingCenterProductRequest request) {
            object[] results = this.Invoke("AdviseClearingCenterProduct", new object[] {
                        request});
            return ((ResponseResult)(results[0]));
        }
        
        /// <remarks/>
        public void AdviseClearingCenterProductAsync(AdviseClearingCenterProductRequest request) {
            this.AdviseClearingCenterProductAsync(request, null);
        }
        
        /// <remarks/>
        public void AdviseClearingCenterProductAsync(AdviseClearingCenterProductRequest request, object userState) {
            if ((this.AdviseClearingCenterProductOperationCompleted == null)) {
                this.AdviseClearingCenterProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdviseClearingCenterProductOperationCompleted);
            }
            this.InvokeAsync("AdviseClearingCenterProduct", new object[] {
                        request}, this.AdviseClearingCenterProductOperationCompleted, userState);
        }
        
        private void OnAdviseClearingCenterProductOperationCompleted(object arg) {
            if ((this.AdviseClearingCenterProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdviseClearingCenterProductCompleted(this, new AdviseClearingCenterProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiAuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://h41201.www4.hp.com/ClearingCenter.Web/WebServices/GetReceivedProducts", RequestNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", ResponseNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetProductListResponse GetReceivedProducts(GetProductListRequest request) {
            object[] results = this.Invoke("GetReceivedProducts", new object[] {
                        request});
            return ((GetProductListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedProductsAsync(GetProductListRequest request) {
            this.GetReceivedProductsAsync(request, null);
        }
        
        /// <remarks/>
        public void GetReceivedProductsAsync(GetProductListRequest request, object userState) {
            if ((this.GetReceivedProductsOperationCompleted == null)) {
                this.GetReceivedProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedProductsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedProducts", new object[] {
                        request}, this.GetReceivedProductsOperationCompleted, userState);
        }
        
        private void OnGetReceivedProductsOperationCompleted(object arg) {
            if ((this.GetReceivedProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedProductsCompleted(this, new GetReceivedProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiAuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://h41201.www4.hp.com/ClearingCenter.Web/WebServices/GetClearedProducts", RequestNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", ResponseNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetProductListResponse GetClearedProducts(GetProductListRequest request) {
            object[] results = this.Invoke("GetClearedProducts", new object[] {
                        request});
            return ((GetProductListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetClearedProductsAsync(GetProductListRequest request) {
            this.GetClearedProductsAsync(request, null);
        }
        
        /// <remarks/>
        public void GetClearedProductsAsync(GetProductListRequest request, object userState) {
            if ((this.GetClearedProductsOperationCompleted == null)) {
                this.GetClearedProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClearedProductsOperationCompleted);
            }
            this.InvokeAsync("GetClearedProducts", new object[] {
                        request}, this.GetClearedProductsOperationCompleted, userState);
        }
        
        private void OnGetClearedProductsOperationCompleted(object arg) {
            if ((this.GetClearedProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClearedProductsCompleted(this, new GetClearedProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiAuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://h41201.www4.hp.com/ClearingCenter.Web/WebServices/ConfirmReceivedProductsR" +
            "eception", RequestNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", ResponseNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseResult ConfirmReceivedProductsReception(ConfirmProcessStatusReceptionRequest request) {
            object[] results = this.Invoke("ConfirmReceivedProductsReception", new object[] {
                        request});
            return ((ResponseResult)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmReceivedProductsReceptionAsync(ConfirmProcessStatusReceptionRequest request) {
            this.ConfirmReceivedProductsReceptionAsync(request, null);
        }
        
        /// <remarks/>
        public void ConfirmReceivedProductsReceptionAsync(ConfirmProcessStatusReceptionRequest request, object userState) {
            if ((this.ConfirmReceivedProductsReceptionOperationCompleted == null)) {
                this.ConfirmReceivedProductsReceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmReceivedProductsReceptionOperationCompleted);
            }
            this.InvokeAsync("ConfirmReceivedProductsReception", new object[] {
                        request}, this.ConfirmReceivedProductsReceptionOperationCompleted, userState);
        }
        
        private void OnConfirmReceivedProductsReceptionOperationCompleted(object arg) {
            if ((this.ConfirmReceivedProductsReceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmReceivedProductsReceptionCompleted(this, new ConfirmReceivedProductsReceptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiAuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://h41201.www4.hp.com/ClearingCenter.Web/WebServices/ConfirmClearedProductsRe" +
            "ception", RequestNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", ResponseNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseResult ConfirmClearedProductsReception(ConfirmProcessStatusReceptionRequest request) {
            object[] results = this.Invoke("ConfirmClearedProductsReception", new object[] {
                        request});
            return ((ResponseResult)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmClearedProductsReceptionAsync(ConfirmProcessStatusReceptionRequest request) {
            this.ConfirmClearedProductsReceptionAsync(request, null);
        }
        
        /// <remarks/>
        public void ConfirmClearedProductsReceptionAsync(ConfirmProcessStatusReceptionRequest request, object userState) {
            if ((this.ConfirmClearedProductsReceptionOperationCompleted == null)) {
                this.ConfirmClearedProductsReceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmClearedProductsReceptionOperationCompleted);
            }
            this.InvokeAsync("ConfirmClearedProductsReception", new object[] {
                        request}, this.ConfirmClearedProductsReceptionOperationCompleted, userState);
        }
        
        private void OnConfirmClearedProductsReceptionOperationCompleted(object arg) {
            if ((this.ConfirmClearedProductsReceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmClearedProductsReceptionCompleted(this, new ConfirmClearedProductsReceptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiAuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://h41201.www4.hp.com/ClearingCenter.Web/WebServices/Echo", RequestNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", ResponseNamespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseResult Echo(EchoRequest request) {
            object[] results = this.Invoke("Echo", new object[] {
                        request});
            return ((ResponseResult)(results[0]));
        }
        
        /// <remarks/>
        public void EchoAsync(EchoRequest request) {
            this.EchoAsync(request, null);
        }
        
        /// <remarks/>
        public void EchoAsync(EchoRequest request, object userState) {
            if ((this.EchoOperationCompleted == null)) {
                this.EchoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEchoOperationCompleted);
            }
            this.InvokeAsync("Echo", new object[] {
                        request}, this.EchoOperationCompleted, userState);
        }
        
        private void OnEchoOperationCompleted(object arg) {
            if ((this.EchoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EchoCompleted(this, new EchoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices", IsNullable=false)]
    public partial class ApiAuthenticationToken : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string apiKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string ApiKey {
            get {
                return this.apiKeyField;
            }
            set {
                this.apiKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class EchoRequest {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class ConfirmProcessStatusReceptionRequest {
        
        private string[] transportIdsField;
        
        /// <remarks/>
        public string[] TransportIds {
            get {
                return this.transportIdsField;
            }
            set {
                this.transportIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class ProductGroupData {
        
        private int idField;
        
        private string externalCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalCode {
            get {
                return this.externalCodeField;
            }
            set {
                this.externalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class StatusData {
        
        private bool isSuccessfulField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private System.DateTime datestampField;
        
        private string updatedByField;
        
        private string remarksField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Datestamp {
            get {
                return this.datestampField;
            }
            set {
                this.datestampField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class TransportProcessData {
        
        private int marketingProgramIdField;
        
        private string countryIsoCodeField;
        
        private string offerIdField;
        
        private string quoteNumberField;
        
        private string transportNumberField;
        
        private string manufacturerNameField;
        
        private string productNumberField;
        
        private string productNameField;
        
        private string serialNumberField;
        
        private int quantityField;
        
        private string forwardingInstructionField;
        
        private StatusData receivingStatusField;
        
        private bool isReceivingOkField;
        
        private System.Nullable<System.DateTime> receivingDateField;
        
        private string receivedByField;
        
        private string receivingRemarksField;
        
        private string problemCodeReceivingField;
        
        private StatusData clearingStatusField;
        
        private bool isClearingOkField;
        
        private System.Nullable<System.DateTime> clearingDateField;
        
        private string clearedByField;
        
        private string clearingRemarksField;
        
        private string problemCodeClearingField;
        
        private ProductGroupData productGroupField;
        
        /// <remarks/>
        public int MarketingProgramId {
            get {
                return this.marketingProgramIdField;
            }
            set {
                this.marketingProgramIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryIsoCode {
            get {
                return this.countryIsoCodeField;
            }
            set {
                this.countryIsoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OfferId {
            get {
                return this.offerIdField;
            }
            set {
                this.offerIdField = value;
            }
        }
        
        /// <remarks/>
        public string QuoteNumber {
            get {
                return this.quoteNumberField;
            }
            set {
                this.quoteNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TransportNumber {
            get {
                return this.transportNumberField;
            }
            set {
                this.transportNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ManufacturerName {
            get {
                return this.manufacturerNameField;
            }
            set {
                this.manufacturerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProductNumber {
            get {
                return this.productNumberField;
            }
            set {
                this.productNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string ForwardingInstruction {
            get {
                return this.forwardingInstructionField;
            }
            set {
                this.forwardingInstructionField = value;
            }
        }
        
        /// <remarks/>
        public StatusData ReceivingStatus {
            get {
                return this.receivingStatusField;
            }
            set {
                this.receivingStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool IsReceivingOk {
            get {
                return this.isReceivingOkField;
            }
            set {
                this.isReceivingOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReceivingDate {
            get {
                return this.receivingDateField;
            }
            set {
                this.receivingDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReceivedBy {
            get {
                return this.receivedByField;
            }
            set {
                this.receivedByField = value;
            }
        }
        
        /// <remarks/>
        public string ReceivingRemarks {
            get {
                return this.receivingRemarksField;
            }
            set {
                this.receivingRemarksField = value;
            }
        }
        
        /// <remarks/>
        public string ProblemCodeReceiving {
            get {
                return this.problemCodeReceivingField;
            }
            set {
                this.problemCodeReceivingField = value;
            }
        }
        
        /// <remarks/>
        public StatusData ClearingStatus {
            get {
                return this.clearingStatusField;
            }
            set {
                this.clearingStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool IsClearingOk {
            get {
                return this.isClearingOkField;
            }
            set {
                this.isClearingOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ClearingDate {
            get {
                return this.clearingDateField;
            }
            set {
                this.clearingDateField = value;
            }
        }
        
        /// <remarks/>
        public string ClearedBy {
            get {
                return this.clearedByField;
            }
            set {
                this.clearedByField = value;
            }
        }
        
        /// <remarks/>
        public string ClearingRemarks {
            get {
                return this.clearingRemarksField;
            }
            set {
                this.clearingRemarksField = value;
            }
        }
        
        /// <remarks/>
        public string ProblemCodeClearing {
            get {
                return this.problemCodeClearingField;
            }
            set {
                this.problemCodeClearingField = value;
            }
        }
        
        /// <remarks/>
        public ProductGroupData ProductGroup {
            get {
                return this.productGroupField;
            }
            set {
                this.productGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class GetProductListResponse {
        
        private TransportProcessData[] transportsField;
        
        private ResponseResult resultField;
        
        /// <remarks/>
        public TransportProcessData[] Transports {
            get {
                return this.transportsField;
            }
            set {
                this.transportsField = value;
            }
        }
        
        /// <remarks/>
        public ResponseResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class ResponseResult {
        
        private bool isSuccessfulField;
        
        private string[] errorMessagesField;
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string[] ErrorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                this.errorMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class GetProductListRequest {
        
        private string marketingProgramIdField;
        
        private string countryIsoCodeField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        /// <remarks/>
        public string MarketingProgramId {
            get {
                return this.marketingProgramIdField;
            }
            set {
                this.marketingProgramIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryIsoCode {
            get {
                return this.countryIsoCodeField;
            }
            set {
                this.countryIsoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class CustomAttribute {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class Product {
        
        private System.Nullable<int> productIdField;
        
        private string manufacturerField;
        
        private string modelField;
        
        private string partNumberField;
        
        private System.Nullable<int> manufacturingYearField;
        
        private string countryOfOriginField;
        
        private string serialNumberField;
        
        private System.Nullable<int> widthField;
        
        private System.Nullable<int> heightField;
        
        private System.Nullable<int> lengthField;
        
        private string lengthUnitField;
        
        private System.Nullable<int> weightField;
        
        private string weightUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ManufacturingYear {
            get {
                return this.manufacturingYearField;
            }
            set {
                this.manufacturingYearField = value;
            }
        }
        
        /// <remarks/>
        public string CountryOfOrigin {
            get {
                return this.countryOfOriginField;
            }
            set {
                this.countryOfOriginField = value;
            }
        }
        
        /// <remarks/>
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string LengthUnit {
            get {
                return this.lengthUnitField;
            }
            set {
                this.lengthUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string WeightUnit {
            get {
                return this.weightUnitField;
            }
            set {
                this.weightUnitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class OrderPosition {
        
        private string transportNumberField;
        
        private int productGroupIdField;
        
        private string clearingCenterIdField;
        
        private int quantityField;
        
        private string transactionDetailIdField;
        
        private Product productField;
        
        private ContactAddress pickupAddressField;
        
        private System.DateTime pickupDateField;
        
        private System.Nullable<System.DateTime> expectedArrivalDateField;
        
        private CustomAttribute[] clearingProcessAttributesField;
        
        /// <remarks/>
        public string TransportNumber {
            get {
                return this.transportNumberField;
            }
            set {
                this.transportNumberField = value;
            }
        }
        
        /// <remarks/>
        public int ProductGroupId {
            get {
                return this.productGroupIdField;
            }
            set {
                this.productGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public string ClearingCenterId {
            get {
                return this.clearingCenterIdField;
            }
            set {
                this.clearingCenterIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDetailId {
            get {
                return this.transactionDetailIdField;
            }
            set {
                this.transactionDetailIdField = value;
            }
        }
        
        /// <remarks/>
        public Product Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        public ContactAddress PickupAddress {
            get {
                return this.pickupAddressField;
            }
            set {
                this.pickupAddressField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PickupDate {
            get {
                return this.pickupDateField;
            }
            set {
                this.pickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpectedArrivalDate {
            get {
                return this.expectedArrivalDateField;
            }
            set {
                this.expectedArrivalDateField = value;
            }
        }
        
        /// <remarks/>
        public CustomAttribute[] ClearingProcessAttributes {
            get {
                return this.clearingProcessAttributesField;
            }
            set {
                this.clearingProcessAttributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class ContactAddress {
        
        private string customerNameField;
        
        private string companyNameField;
        
        private string streetAddress01Field;
        
        private string streetAddress02Field;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string stateOrProvinceField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress01 {
            get {
                return this.streetAddress01Field;
            }
            set {
                this.streetAddress01Field = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress02 {
            get {
                return this.streetAddress02Field;
            }
            set {
                this.streetAddress02Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvince {
            get {
                return this.stateOrProvinceField;
            }
            set {
                this.stateOrProvinceField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class Order {
        
        private string marketingProgramIdField;
        
        private string countryIsoCodeField;
        
        private string offerIdField;
        
        private string quoteNumberField;
        
        private System.DateTime orderDateField;
        
        private ContactAddress customerDataField;
        
        private OrderPosition[] positionsField;
        
        /// <remarks/>
        public string MarketingProgramId {
            get {
                return this.marketingProgramIdField;
            }
            set {
                this.marketingProgramIdField = value;
            }
        }
        
        /// <remarks/>
        public string CountryIsoCode {
            get {
                return this.countryIsoCodeField;
            }
            set {
                this.countryIsoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OfferId {
            get {
                return this.offerIdField;
            }
            set {
                this.offerIdField = value;
            }
        }
        
        /// <remarks/>
        public string QuoteNumber {
            get {
                return this.quoteNumberField;
            }
            set {
                this.quoteNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public ContactAddress CustomerData {
            get {
                return this.customerDataField;
            }
            set {
                this.customerDataField = value;
            }
        }
        
        /// <remarks/>
        public OrderPosition[] Positions {
            get {
                return this.positionsField;
            }
            set {
                this.positionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://h41201.www4.hp.com/ClearingCenter.Web/WebServices")]
    public partial class AdviseClearingCenterProductRequest {
        
        private Order orderField;
        
        /// <remarks/>
        public Order Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void AdviseClearingCenterProductCompletedEventHandler(object sender, AdviseClearingCenterProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdviseClearingCenterProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdviseClearingCenterProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetReceivedProductsCompletedEventHandler(object sender, GetReceivedProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetClearedProductsCompletedEventHandler(object sender, GetClearedProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClearedProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClearedProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConfirmReceivedProductsReceptionCompletedEventHandler(object sender, ConfirmReceivedProductsReceptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmReceivedProductsReceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmReceivedProductsReceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConfirmClearedProductsReceptionCompletedEventHandler(object sender, ConfirmClearedProductsReceptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmClearedProductsReceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmClearedProductsReceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EchoCompletedEventHandler(object sender, EchoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EchoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EchoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591